// Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include <stdio.h>

#include "cras_messages.h"
#include "cras_shm.h"
#include "cras_types.h"

#define DUMP_SIZE(S) printf("%s;%zu\n", #S, sizeof(S))

int main()
{
	/* Dump structures size, generated by:
	   cd cras/src/common; for header in *.h ; do
	     echo "\t// --- $header ---"
	     sed -n 's/^struct.* \([^ ]*\) {/\tDUMP_SIZE(struct \1);/p' \
	     "$header"
	   done
	   Then remove structures that are local
	*/

	// --- cras_audio_codec.h ---
	//   struct cras_audio_codec: local
	// --- cras_audio_format.h ---
	//   struct cras_audio_format: shared with applications
	DUMP_SIZE(struct cras_audio_format_packed);
	// --- cras_iodev_info.h ---
	DUMP_SIZE(struct cras_iodev_info);
	DUMP_SIZE(struct cras_ionode_info);
	// --- cras_messages.h ---
	DUMP_SIZE(struct cras_server_message);
	DUMP_SIZE(struct cras_client_message);
	DUMP_SIZE(struct cras_connect_message);
	DUMP_SIZE(struct cras_disconnect_stream_message);
	DUMP_SIZE(struct cras_switch_stream_type_iodev);
	DUMP_SIZE(struct cras_set_system_volume);
	DUMP_SIZE(struct cras_set_system_capture_gain);
	DUMP_SIZE(struct cras_set_system_mute);
	DUMP_SIZE(struct cras_set_node_attr);
	DUMP_SIZE(struct cras_select_node);
	DUMP_SIZE(struct cras_reload_dsp);
	DUMP_SIZE(struct cras_dump_dsp_info);
	DUMP_SIZE(struct cras_dump_audio_thread);
	DUMP_SIZE(struct cras_client_connected);
	DUMP_SIZE(struct cras_client_stream_connected);
	DUMP_SIZE(struct cras_client_stream_reattach);
	DUMP_SIZE(struct cras_client_audio_debug_info_ready);
	DUMP_SIZE(struct audio_message);
	// --- cras_shm.h ---
	DUMP_SIZE(struct cras_audio_shm_config);
	DUMP_SIZE(struct cras_audio_shm_area);
	// struct cras_audio_shm: local
	// --- cras_types.h ---
	DUMP_SIZE(struct cras_timespec);
	DUMP_SIZE(struct cras_attached_client_info);
	DUMP_SIZE(struct audio_thread_event_log);
	DUMP_SIZE(struct audio_stream_debug_info);
	DUMP_SIZE(struct audio_debug_info);
	DUMP_SIZE(struct cras_server_state);
	DUMP_SIZE(struct cras_alsa_card_info);
	// --- dumper.h: local ---
	// --- rtp.h: local ---

	return 0;
}
